
# Key Bindings
# key name refer to `xev` or `wev` command output,
# mod keys name: super,ctrl,alt,shift,none

# reload config
bind=SUPER+CTRL+ALT,delete,reload_config

# app shortcuts
bind=SUPER,space,spawn,app2unit -- fuzzel
bind=SUPER,t,spawn,app2unit -T
bind=SUPER,b,spawn,app2unit -- waterfox
bind=SUPER,e,spawn,app2unit -- nemo
z
# exit
bind=SUPER,delete,loginctl terminate-user
bind=SUPER,q,killclient,

# switch window focus
bind=SUPER,Tab,focusstack,next
bind=SUPER,Left,focusdir,left
bind=SUPER,Right,focusdir,right
bind=SUPER,Up,focusdir,up
bind=SUPER,Down,focusdir,down

# swap window
bind=SUPER+SHIFT,Up,exchange_client,up
bind=SUPER+SHIFT,Down,exchange_client,down
bind=SUPER+SHIFT,Left,exchange_client,left
bind=SUPER+SHIFT,Right,exchange_client,right

# toggle windows status
bind=SUPER,g,toggleglobal,
bind=ALT,Tab,toggleoverview,
bind=SUPER,f,togglefloating,
bind=SUPER,m,togglemaximizescreen,
bind=SUPER,F11,togglefullscreen,
bind=SUPER+SHIFT,F11,togglefakefullscreen,
bind=SUPER,i,minimized,
bind=SUPER,o,toggleoverlay,
bind=SUPER+SHIFT,I,restore_minimized
bind=SUPER,z,toggle_scratchpad

# scroller layout
bind=SUPER,r,switch_proportion_preset,

# switch layout
bind=SUPER,n,switch_layout

# tag switch
bind=SUPER,Left,viewtoleft,0
#bind=CTRL,Left,viewtoleft_have_client,0
bind=SUPER,Right,viewtoright,0
#bind=CTRL,Right,viewtoright_have_client,0
bind=CTRL+SUPER,Left,tagtoleft,0
bind=CTRL+SUPER,Right,tagtoright,0

bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0

# tag: move client to the tag and focus it
# tagsilent: move client to the tag and not focus it
# bind=Alt,1,tagsilent,1
bind=Alt,1,tag,1,0
bind=Alt,2,tag,2,0
bind=Alt,3,tag,3,0
bind=Alt,4,tag,4,0
bind=Alt,5,tag,5,0
bind=Alt,6,tag,6,0
bind=Alt,7,tag,7,0
bind=Alt,8,tag,8,0
bind=Alt,9,tag,9,0

# monitor switch
bind=alt+shift,Left,focusmon,left
bind=alt+shift,Right,focusmon,right
bind=SUPER+Alt,Left,tagmon,left
bind=SUPER+Alt,Right,tagmon,right

# gaps
#bind=ALT+SHIFT,X,incgaps,1
#bind=ALT+SHIFT,Z,incgaps,-1
#bind=ALT+SHIFT,R,togglegaps

# movewin
#bind=CTRL+SHIFT,Up,movewin,+0,-50
#bind=CTRL+SHIFT,Down,movewin,+0,+50
#bind=CTRL+SHIFT,Left,movewin,-50,+0
#bind=CTRL+SHIFT,Right,movewin,+50,+0

# resizewin
#bind=CTRL+ALT,Up,resizewin,+0,-50
#bind=CTRL+ALT,Down,resizewin,+0,+50
#bind=CTRL+ALT,Left,resizewin,-50,+0
#bind=CTRL+ALT,Right,resizewin,+50,+0

# Mouse Button Bindings
# btn_left and btn_right can't bind none mod key
mousebind=SUPER,btn_left,moveresize,curmove
#mousebind=NONE,btn_middle,togglemaximizescreen,0
mousebind=SUPER,btn_right,moveresize,curresize

# Axis Bindings
axisbind=SUPER,UP,viewtoleft_have_client
axisbind=SUPER,DOWN,viewtoright_have_client

# Gestures
# 3finger: Workspace navigation
gesturebind=none,up,3,viewtoright
gesturebind=none,down,3,viewtoleft

gesturebind=none,left,3,focusdir,left
gesturebind=none,right,3,focusdir,right

# Function keys
# Brigtness
bind=NONE,XF86MonBrightnessUp,spawn,brightnessctl s +10%
bind=SHIFT,XF86MonBrightnessUp,spawn,brightnessctl s 100%
bind=NONE,XF86MonBrightnessDown,spawn,brightnessctl s 10%-
bind=SHIFT,XF86MonBrightnessDown,spawn,brightnessctl s 0%

# Volume
bind=NONE,XF86AudioRaiseVolume,spawn,wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bind=NONE,XF86AudioLowerVolume,spawn,wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%-
bind=NONE,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_SINK@ toggle
bind=SHIFT,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_SOURCE@ toggle

# Media
bind=NONE,XF86AudioNext,spawn,playerctl next
bind=NONE,XF86AudioPlay,spawn,playerctl play-pause
bind=NONE,XF86AudioPause,spawn,playerctl play-pause
bind=NONE,XF86AudioPrev,spawn,playerctl previous
