# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x1e1e2eff
rootcolor = 0x24273aff
bordercolor = 0x6a6f93ff
focuscolor = 0x94e2d5ff
maximizescreencolor = 0x89b4faff
urgentcolor = 0xf38ba8ff
scratchpadcolor = 0xc6a0f6ff
globalcolor = 0x1ba891ff
overlaycolor = 0x004fd0ff
